language: julia

os:
    - linux
    - osx

julia:
    - 1.0
    - 1.1
    - nightly

# Pin MbedTLS due to issue:
#   https://github.com/JuliaWeb/MbedTLS.jl/issues/193
before_script:
  - julia -e 'using Pkg;
      Pkg.add(PackageSpec(name="MbedTLS", version="0.6.6"));
      Pkg.pin(PackageSpec(name="MbedTLS", version="0.6.6"));'

codecov: true
coveralls: true

matrix:
    allow_failures:
        - julia: nightly

notifications:
    email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs/ --color=yes docs/make.jl
      after_success: skip
