language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - nightly
matrix:
    allow_failures:
        - julia: nightly
after_success:
    # Push coverage results to Coveralls.
    - julia -e 'cd(Pkg.dir("ReferenceFrameRotations")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
    # Compile and deploy the documentation.
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'cd(Pkg.dir("ReferenceFrameRotations")); include(joinpath("docs", "make.jl"))'
notifications:
    email: false
